#微服务配置
spring:
  application:
    name: bootWebPlus
  # spring数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: 123456
  # springfox-boot-starter (Swagger 3.0)Springfox 使用的路径匹配是基于AntPathMatcher的，
  # 而Spring Boot 2.6.X使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# swagger 文档配置
swagger:
  title: "书本管理系统"
  description: "管理数据"
  base-package: com.example.bootwebplus
  version: 1.0.0
  terms-of-service-url: http://127.0.0.1:8080/tblBook
  contact:
    email: book@mail.com
    name: 树人
    url: https://www.baidu.com
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml